### ISSUE TITLE
博主你好 这个项目我的action会失败

### ISSUE THREAD

**Issue by tovarsh** [xaoxuu/ghapi-json-generator#1]
https://github.com/ThatCoders/ghapi-json-generator/actions/runs/4035941232

博主您能帮看看吗, 每次关于抓取数据输出output分支的项目都会在action **build**中** Commit & Push**失败, 这是错误链接

**Comment by xaoxuu** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/16400144/215322016-2393d4c0-9c3d-4674-8a8b-9c143b620cc2.png">
错误原因是没有 push 权限

**Comment by tovarsh** [comment]
> <img width="900" alt="image" src="https://user-images.githubusercontent.com/16400144/215322016-2393d4c0-9c3d-4674-8a8b-9c143b620cc2.png">
> 错误原因是没有 push 权限

还是没发现哪里能给它权限，除了readme说的还需要给什么参数变量吗

**Comment by xaoxuu** [comment]
https://github.com/orgs/community/discussions/26694 看看这个能不能帮到你

**Comment by tovarsh** [comment]
> https://github.com/orgs/community/discussions/26694 看看这个能不能帮到你

谢谢大佬我解决了, 我已经有个[类似的项目](https://github.com/ThatCoders/hexo-issuse-friends)能跑.
就按那个仓库的设置去配一遍这个仓库就好了.
