### ISSUE TITLE
Rate Limit 60

### ISSUE THREAD

**Issue by libsgh** [xaoxuu/ghapi-json-generator#2]
配置里只有三个地址，看了下日志也是每小时执行一次，但还会有Rate Limit 60，猜测Action Runner IP会共用导致这种情况？
能否增加个配置`access_token`

- 未经身份验证 - 每个原始 IP 地址每小时60个请求
- 已验证 – 每个用户每小时可发送 5,000 个请求

**Comment by xaoxuu** [comment]
已经加好了： https://github.com/xaoxuu/ghapi-json-generator/actions/runs/7741340059/job/21108160005

虽然这个验证的是1000条，但也够用了吧

**Comment by libsgh** [comment]
Nice.1000够用了，而且不用额外配置.
